### ISSUE TITLE
db-journey Cassandra driver broken

### ISSUE THREAD

**Issue by sonalramnani** [db-journey/cassandra-driver#4] opened 2017-10-26 04:14 UTC
Hi,

dn-journey Cassandra driver will not compile due to commit 21155bbe01c45da476e9359d2c39d60193edca7e 
line 45: consistency, err := gocql.ParseConsistency(consistencyStr)

gocql.ParseConsistency returns 1 value. this line of code is expecting 2 return values. Exact line of output from the build:
/go/src/github.com/db-journey/cassandra-driver/cassandra.go:45: assignment count mismatch: 2 = 1

**Comment by gravis** [comment] 2017-10-26 11:44
Duplicate of #1 
Please update your deps.
Thanks

**Comment by sonalramnani** [comment] 2017-10-26 15:45
I don't see how this could work with the current code in the repo. 

https://github.com/gocql/gocql/blob/master/frame.go - ParseConsistency returns 1 value:

func ParseConsistency(s string) Consistency {
	var c Consistency
	if err := c.UnmarshalText([]byte(strings.ToUpper(s))); err != nil {
		panic(err)
	}
	return c
}

Your code: consistency, err := gocql.ParseConsistency(consistencyStr) expects 2 return values

**Comment by aliaksandrb** [comment] 2017-10-26 15:54
Hi @gravis !

Unfortunately the `gocql` reverted their change back (just 16 hours ago https://github.com/gocql/gocql/commit/939af06b39e61c17b91b7c11720213246ece9b80 )

So probably this driver should do that as well :D

**Comment by gravis** [comment] 2017-10-26 16:16
Ha, that was unexpected :)
I will revert the change too then!
Thanks @aliaksandrb for pointing this.

**Closed** 2017-10-27 13:21 UTC
